[phases.setup]
nixPkgs = ["tesseract", "poppler", "libGL", "glib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
nixPkgs = ["tesseract", "poppler_utils", "libgl1", "libglib2.0", "gcc", "gxx"]
